/* This file is automatically generated by Lemon from input grammar
** source file "grammar/cypher.lemon".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 15 "grammar/cypher.lemon"

#include "cypher.h"
#include <string.h>
#include <assert.h>

/* Parser state structure passed to all grammar rules */
struct CypherParseState {
  CypherParser *pParser;
  CypherAst *pResult;
  char *zError;
};

/* Forward declarations for AST functions */
CypherAst *cypherAstCreateIdentifier(const char *zName, int iLine, int iColumn);
CypherAst *cypherAstCreateLiteral(const char *zValue, int iLine, int iColumn);
CypherAst *cypherAstCreateBinaryOp(const char *zOp, CypherAst *pLeft, CypherAst *pRight, int iLine, int iColumn);
CypherAst *cypherAstCreateProperty(CypherAst *pObj, const char *zProp, int iLine, int iColumn);
#line 48 "grammar/cypher.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef CREATE
#define CREATE                          1
#define MERGE                           2
#define SET                             3
#define DELETE                          4
#define REMOVE                          5
#define WITH                            6
#define LBRACE                          7
#define RBRACE                          8
#define UNION                           9
#define MATCH                          10
#define OPTIONAL                       11
#define COMMA                          12
#define LPAREN                         13
#define RPAREN                         14
#define IDENTIFIER                     15
#define COLON                          16
#define DASH                           17
#define LBRACKET                       18
#define RBRACKET                       19
#define ARROW_RIGHT                    20
#define ARROW_LEFT                     21
#define WHERE                          22
#define RETURN                         23
#define DISTINCT                       24
#define AS                             25
#define ORDER                          26
#define BY                             27
#define ASC                            28
#define DESC                           29
#define LIMIT                          30
#define INTEGER                        31
#define SKIP                           32
#define OR                             33
#define AND                            34
#define EQ                             35
#define NE                             36
#define LT                             37
#define LE                             38
#define GT                             39
#define GE                             40
#define PLUS                           41
#define MINUS                          42
#define MULT                           43
#define DIV                            44
#define NOT                            45
#define DOT                            46
#define FLOAT                          47
#define STRING                         48
#define BOOLEAN                        49
#define NULL                           50
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 83
#define YYACTIONTYPE unsigned short int
#define ParseTOKENTYPE CypherToken*
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
  CypherAst* yy8;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL struct CypherParseState *pState;
#define ParseARG_PDECL ,struct CypherParseState *pState
#define ParseARG_PARAM ,pState
#define ParseARG_FETCH struct CypherParseState *pState=yypParser->pState;
#define ParseARG_STORE yypParser->pState=pState;
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYNSTATE             84
#define YYNRULE              76
#define YYNRULE_WITH_ACTION  76
#define YYNTOKEN             51
#define YY_MAX_SHIFT         83
#define YY_MIN_SHIFTREDUCE   131
#define YY_MAX_SHIFTREDUCE   206
#define YY_ERROR_ACTION      207
#define YY_ACCEPT_ACTION     208
#define YY_NO_ACTION         209
#define YY_MIN_REDUCE        210
#define YY_MAX_REDUCE        285
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (294)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */    54,   55,  242,  226,   30,   79,   75,   46,   32,   40,
 /*    10 */    43,  270,  273,  276,  278,   54,   52,  242,  150,   29,
 /*    20 */    79,   75,   46,   32,   40,   43,  270,  273,  276,  278,
 /*    30 */    50,  171,  172,   80,  247,   79,   75,   46,   32,   40,
 /*    40 */    43,  270,  273,  276,  278,   54,  157,  243,   39,  158,
 /*    50 */    79,   75,   46,   32,   40,   43,  270,  273,  276,  278,
 /*    60 */    50,  275,  276,  278,  248,   79,   75,   46,   32,   40,
 /*    70 */    43,  270,  273,  276,  278,  239,  272,  273,  276,  278,
 /*    80 */    79,   75,   46,   32,   40,   43,  270,  273,  276,  278,
 /*    90 */    74,  271,  273,  276,  278,   79,   75,   46,   32,   40,
 /*   100 */    43,  270,  273,  276,  278,   27,   57,   27,   57,    7,
 /*   110 */    38,   77,  208,   83,   82,   51,   22,    6,    1,    6,
 /*   120 */     2,  219,  221,  222,  274,  276,  278,  202,   41,   43,
 /*   130 */   270,  273,  276,  278,    7,  228,   77,  151,   23,   69,
 /*   140 */   152,   24,   70,  203,  204,  205,  206,   44,  270,  273,
 /*   150 */   276,  278,  202,   42,   43,  270,  273,  276,  278,   15,
 /*   160 */    14,   13,   12,   23,   11,   10,   24,   31,  203,  204,
 /*   170 */   205,  206,   78,   46,   32,   40,   43,  270,  273,  276,
 /*   180 */   278,   18,  216,  217,  218,   49,   32,   40,   43,  270,
 /*   190 */   273,  276,  278,   33,   40,   43,  270,  273,  276,  278,
 /*   200 */    34,   40,   43,  270,  273,  276,  278,    7,    4,   77,
 /*   210 */    45,   43,  270,  273,  276,  278,   48,   43,  270,  273,
 /*   220 */   276,  278,   56,  225,   30,  202,   47,  270,  273,  276,
 /*   230 */   278,  214,  166,   22,   71,  225,   30,   53,  219,  221,
 /*   240 */   222,  203,  204,  205,  206,  213,   68,   22,   17,   16,
 /*   250 */    63,   25,  219,  221,  222,  220,  221,  222,   81,   28,
 /*   260 */    65,   36,   73,   66,   72,   67,   21,   20,   26,  159,
 /*   270 */    58,   59,   62,   60,   61,    9,   64,  153,    8,   35,
 /*   280 */   156,  155,  154,   37,  174,  200,  173,  201,   76,    5,
 /*   290 */    19,  210,  209,    3,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    68,   69,   70,   64,   65,   73,   74,   75,   76,   77,
 /*    10 */    78,   79,   80,   81,   82,   68,   69,   70,   14,   15,
 /*    20 */    73,   74,   75,   76,   77,   78,   79,   80,   81,   82,
 /*    30 */    68,   28,   29,   71,   72,   73,   74,   75,   76,   77,
 /*    40 */    78,   79,   80,   81,   82,   68,   17,   70,   13,   20,
 /*    50 */    73,   74,   75,   76,   77,   78,   79,   80,   81,   82,
 /*    60 */    68,   80,   81,   82,   72,   73,   74,   75,   76,   77,
 /*    70 */    78,   79,   80,   81,   82,   68,   79,   80,   81,   82,
 /*    80 */    73,   74,   75,   76,   77,   78,   79,   80,   81,   82,
 /*    90 */    68,   79,   80,   81,   82,   73,   74,   75,   76,   77,
 /*   100 */    78,   79,   80,   81,   82,   10,   11,   10,   11,   13,
 /*   110 */    67,   15,   51,   52,   53,   54,   55,   22,   23,   22,
 /*   120 */    24,   60,   61,   62,   80,   81,   82,   31,   77,   78,
 /*   130 */    79,   80,   81,   82,   13,   65,   15,   14,   42,   16,
 /*   140 */    14,   45,   16,   47,   48,   49,   50,   78,   79,   80,
 /*   150 */    81,   82,   31,   77,   78,   79,   80,   81,   82,   37,
 /*   160 */    38,   39,   40,   42,   35,   36,   45,   66,   47,   48,
 /*   170 */    49,   50,   74,   75,   76,   77,   78,   79,   80,   81,
 /*   180 */    82,    9,   57,   58,   59,   75,   76,   77,   78,   79,
 /*   190 */    80,   81,   82,   76,   77,   78,   79,   80,   81,   82,
 /*   200 */    76,   77,   78,   79,   80,   81,   82,   13,   12,   15,
 /*   210 */    77,   78,   79,   80,   81,   82,   77,   78,   79,   80,
 /*   220 */    81,   82,   63,   64,   65,   31,   78,   79,   80,   81,
 /*   230 */    82,   53,   15,   55,   63,   64,   65,   25,   60,   61,
 /*   240 */    62,   47,   48,   49,   50,   53,   17,   55,   41,   42,
 /*   250 */    21,   56,   60,   61,   62,   60,   61,   62,   26,   12,
 /*   260 */    16,   15,   30,   19,   32,   19,   43,   44,   10,   17,
 /*   270 */    19,   15,   18,   16,   15,   34,   15,   15,   33,   19,
 /*   280 */    17,   17,   15,   18,   31,   14,   31,   15,   46,   12,
 /*   290 */     9,    0,   83,   27,   83,   83,   83,   83,   83,   83,
 /*   300 */    83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
 /*   310 */    83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
 /*   320 */    83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
 /*   330 */    83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
 /*   340 */    83,   83,   83,   83,   83,
};
#define YY_SHIFT_COUNT    (83)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (291)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */    97,   96,  121,  121,  121,  121,  121,  121,  121,  121,
 /*    10 */   121,  121,  121,  121,  121,  121,  121,  121,   97,   97,
 /*    20 */   121,  121,   95,  194,  194,  232,   35,   35,   35,  123,
 /*    30 */   229,   35,  122,  122,  122,   29,  244,  246,  126,    4,
 /*    40 */   207,  207,  207,  223,  223,  207,  129,  223,  207,  129,
 /*    50 */     3,  172,  196,  217,  212,  196,  247,  258,  252,  251,
 /*    60 */   256,  257,  259,  254,  260,  261,  263,  264,  265,  262,
 /*    70 */   267,  247,  253,  255,  271,  241,  272,  242,  241,  245,
 /*    80 */   277,  266,  281,  291,
};
#define YY_REDUCE_COUNT (31)
#define YY_REDUCE_MIN   (-68)
#define YY_REDUCE_MAX   (195)
static const short yy_reduce_ofst[] = {
 /*     0 */    61,  -68,  -53,  -38,  -23,   -8,    7,   22,   98,  110,
 /*    10 */   117,  124,   51,   76,  133,  139,   69,  148,  178,  192,
 /*    20 */    -3,   12,  195,  -19,   44,  125,  159,  171,  -61,   43,
 /*    30 */   101,   70,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
 /*    10 */   207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
 /*    20 */   207,  207,  207,  207,  207,  215,  207,  207,  207,  207,
 /*    30 */   227,  207,  259,  261,  260,  207,  207,  207,  207,  207,
 /*    40 */   262,  266,  265,  267,  269,  264,  257,  268,  263,  258,
 /*    50 */   249,  212,  241,  207,  244,  240,  224,  207,  207,  207,
 /*    60 */   207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
 /*    70 */   207,  223,  207,  207,  207,  255,  207,  277,  256,  254,
 /*    80 */   246,  207,  211,  207,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "CREATE",
  /*    2 */ "MERGE",
  /*    3 */ "SET",
  /*    4 */ "DELETE",
  /*    5 */ "REMOVE",
  /*    6 */ "WITH",
  /*    7 */ "LBRACE",
  /*    8 */ "RBRACE",
  /*    9 */ "UNION",
  /*   10 */ "MATCH",
  /*   11 */ "OPTIONAL",
  /*   12 */ "COMMA",
  /*   13 */ "LPAREN",
  /*   14 */ "RPAREN",
  /*   15 */ "IDENTIFIER",
  /*   16 */ "COLON",
  /*   17 */ "DASH",
  /*   18 */ "LBRACKET",
  /*   19 */ "RBRACKET",
  /*   20 */ "ARROW_RIGHT",
  /*   21 */ "ARROW_LEFT",
  /*   22 */ "WHERE",
  /*   23 */ "RETURN",
  /*   24 */ "DISTINCT",
  /*   25 */ "AS",
  /*   26 */ "ORDER",
  /*   27 */ "BY",
  /*   28 */ "ASC",
  /*   29 */ "DESC",
  /*   30 */ "LIMIT",
  /*   31 */ "INTEGER",
  /*   32 */ "SKIP",
  /*   33 */ "OR",
  /*   34 */ "AND",
  /*   35 */ "EQ",
  /*   36 */ "NE",
  /*   37 */ "LT",
  /*   38 */ "LE",
  /*   39 */ "GT",
  /*   40 */ "GE",
  /*   41 */ "PLUS",
  /*   42 */ "MINUS",
  /*   43 */ "MULT",
  /*   44 */ "DIV",
  /*   45 */ "NOT",
  /*   46 */ "DOT",
  /*   47 */ "FLOAT",
  /*   48 */ "STRING",
  /*   49 */ "BOOLEAN",
  /*   50 */ "NULL",
  /*   51 */ "cypher_query",
  /*   52 */ "query",
  /*   53 */ "single_query",
  /*   54 */ "union_query",
  /*   55 */ "reading_clause_list",
  /*   56 */ "return_clause",
  /*   57 */ "order_by_clause",
  /*   58 */ "limit_clause",
  /*   59 */ "skip_clause",
  /*   60 */ "reading_clause",
  /*   61 */ "match_clause",
  /*   62 */ "where_clause",
  /*   63 */ "pattern_list",
  /*   64 */ "pattern",
  /*   65 */ "node_pattern",
  /*   66 */ "relationship_pattern",
  /*   67 */ "node_labels",
  /*   68 */ "expression",
  /*   69 */ "projection_list",
  /*   70 */ "projection_item",
  /*   71 */ "sort_list",
  /*   72 */ "sort_item",
  /*   73 */ "or_expression",
  /*   74 */ "and_expression",
  /*   75 */ "equality_expression",
  /*   76 */ "relational_expression",
  /*   77 */ "additive_expression",
  /*   78 */ "multiplicative_expression",
  /*   79 */ "unary_expression",
  /*   80 */ "primary_expression",
  /*   81 */ "literal",
  /*   82 */ "property_expression",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "cypher_query ::= query",
 /*   1 */ "query ::= single_query",
 /*   2 */ "query ::= union_query",
 /*   3 */ "union_query ::= single_query UNION single_query",
 /*   4 */ "union_query ::= union_query UNION single_query",
 /*   5 */ "single_query ::= reading_clause_list return_clause",
 /*   6 */ "single_query ::= reading_clause_list return_clause order_by_clause",
 /*   7 */ "single_query ::= reading_clause_list return_clause limit_clause",
 /*   8 */ "single_query ::= reading_clause_list return_clause skip_clause",
 /*   9 */ "reading_clause_list ::= reading_clause",
 /*  10 */ "reading_clause_list ::= reading_clause_list reading_clause",
 /*  11 */ "reading_clause ::= match_clause",
 /*  12 */ "reading_clause ::= where_clause",
 /*  13 */ "match_clause ::= MATCH pattern_list",
 /*  14 */ "match_clause ::= OPTIONAL MATCH pattern_list",
 /*  15 */ "pattern_list ::= pattern",
 /*  16 */ "pattern_list ::= pattern_list COMMA pattern",
 /*  17 */ "pattern ::= node_pattern",
 /*  18 */ "pattern ::= node_pattern relationship_pattern node_pattern",
 /*  19 */ "node_pattern ::= LPAREN RPAREN",
 /*  20 */ "node_pattern ::= LPAREN IDENTIFIER RPAREN",
 /*  21 */ "node_pattern ::= LPAREN IDENTIFIER node_labels RPAREN",
 /*  22 */ "node_labels ::= COLON IDENTIFIER",
 /*  23 */ "node_labels ::= node_labels COLON IDENTIFIER",
 /*  24 */ "relationship_pattern ::= DASH LBRACKET RBRACKET DASH",
 /*  25 */ "relationship_pattern ::= DASH LBRACKET IDENTIFIER RBRACKET DASH",
 /*  26 */ "relationship_pattern ::= DASH LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET DASH",
 /*  27 */ "relationship_pattern ::= DASH LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET ARROW_RIGHT",
 /*  28 */ "relationship_pattern ::= ARROW_LEFT LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET DASH",
 /*  29 */ "where_clause ::= WHERE expression",
 /*  30 */ "return_clause ::= RETURN projection_list",
 /*  31 */ "return_clause ::= RETURN DISTINCT projection_list",
 /*  32 */ "projection_list ::= projection_item",
 /*  33 */ "projection_list ::= projection_list COMMA projection_item",
 /*  34 */ "projection_item ::= expression",
 /*  35 */ "projection_item ::= expression AS IDENTIFIER",
 /*  36 */ "order_by_clause ::= ORDER BY sort_list",
 /*  37 */ "sort_list ::= sort_item",
 /*  38 */ "sort_list ::= sort_list COMMA sort_item",
 /*  39 */ "sort_item ::= expression",
 /*  40 */ "sort_item ::= expression ASC",
 /*  41 */ "sort_item ::= expression DESC",
 /*  42 */ "limit_clause ::= LIMIT INTEGER",
 /*  43 */ "skip_clause ::= SKIP INTEGER",
 /*  44 */ "expression ::= or_expression",
 /*  45 */ "or_expression ::= and_expression",
 /*  46 */ "or_expression ::= or_expression OR and_expression",
 /*  47 */ "and_expression ::= equality_expression",
 /*  48 */ "and_expression ::= and_expression AND equality_expression",
 /*  49 */ "equality_expression ::= relational_expression",
 /*  50 */ "equality_expression ::= equality_expression EQ relational_expression",
 /*  51 */ "equality_expression ::= equality_expression NE relational_expression",
 /*  52 */ "relational_expression ::= additive_expression",
 /*  53 */ "relational_expression ::= relational_expression LT additive_expression",
 /*  54 */ "relational_expression ::= relational_expression LE additive_expression",
 /*  55 */ "relational_expression ::= relational_expression GT additive_expression",
 /*  56 */ "relational_expression ::= relational_expression GE additive_expression",
 /*  57 */ "additive_expression ::= multiplicative_expression",
 /*  58 */ "additive_expression ::= additive_expression PLUS multiplicative_expression",
 /*  59 */ "additive_expression ::= additive_expression MINUS multiplicative_expression",
 /*  60 */ "multiplicative_expression ::= unary_expression",
 /*  61 */ "multiplicative_expression ::= multiplicative_expression MULT unary_expression",
 /*  62 */ "multiplicative_expression ::= multiplicative_expression DIV unary_expression",
 /*  63 */ "unary_expression ::= primary_expression",
 /*  64 */ "unary_expression ::= NOT primary_expression",
 /*  65 */ "unary_expression ::= MINUS primary_expression",
 /*  66 */ "primary_expression ::= literal",
 /*  67 */ "primary_expression ::= IDENTIFIER",
 /*  68 */ "primary_expression ::= property_expression",
 /*  69 */ "primary_expression ::= LPAREN expression RPAREN",
 /*  70 */ "property_expression ::= IDENTIFIER DOT IDENTIFIER",
 /*  71 */ "literal ::= INTEGER",
 /*  72 */ "literal ::= FLOAT",
 /*  73 */ "literal ::= STRING",
 /*  74 */ "literal ::= BOOLEAN",
 /*  75 */ "literal ::= NULL",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    51,  /* (0) cypher_query ::= query */
    52,  /* (1) query ::= single_query */
    52,  /* (2) query ::= union_query */
    54,  /* (3) union_query ::= single_query UNION single_query */
    54,  /* (4) union_query ::= union_query UNION single_query */
    53,  /* (5) single_query ::= reading_clause_list return_clause */
    53,  /* (6) single_query ::= reading_clause_list return_clause order_by_clause */
    53,  /* (7) single_query ::= reading_clause_list return_clause limit_clause */
    53,  /* (8) single_query ::= reading_clause_list return_clause skip_clause */
    55,  /* (9) reading_clause_list ::= reading_clause */
    55,  /* (10) reading_clause_list ::= reading_clause_list reading_clause */
    60,  /* (11) reading_clause ::= match_clause */
    60,  /* (12) reading_clause ::= where_clause */
    61,  /* (13) match_clause ::= MATCH pattern_list */
    61,  /* (14) match_clause ::= OPTIONAL MATCH pattern_list */
    63,  /* (15) pattern_list ::= pattern */
    63,  /* (16) pattern_list ::= pattern_list COMMA pattern */
    64,  /* (17) pattern ::= node_pattern */
    64,  /* (18) pattern ::= node_pattern relationship_pattern node_pattern */
    65,  /* (19) node_pattern ::= LPAREN RPAREN */
    65,  /* (20) node_pattern ::= LPAREN IDENTIFIER RPAREN */
    65,  /* (21) node_pattern ::= LPAREN IDENTIFIER node_labels RPAREN */
    67,  /* (22) node_labels ::= COLON IDENTIFIER */
    67,  /* (23) node_labels ::= node_labels COLON IDENTIFIER */
    66,  /* (24) relationship_pattern ::= DASH LBRACKET RBRACKET DASH */
    66,  /* (25) relationship_pattern ::= DASH LBRACKET IDENTIFIER RBRACKET DASH */
    66,  /* (26) relationship_pattern ::= DASH LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET DASH */
    66,  /* (27) relationship_pattern ::= DASH LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET ARROW_RIGHT */
    66,  /* (28) relationship_pattern ::= ARROW_LEFT LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET DASH */
    62,  /* (29) where_clause ::= WHERE expression */
    56,  /* (30) return_clause ::= RETURN projection_list */
    56,  /* (31) return_clause ::= RETURN DISTINCT projection_list */
    69,  /* (32) projection_list ::= projection_item */
    69,  /* (33) projection_list ::= projection_list COMMA projection_item */
    70,  /* (34) projection_item ::= expression */
    70,  /* (35) projection_item ::= expression AS IDENTIFIER */
    57,  /* (36) order_by_clause ::= ORDER BY sort_list */
    71,  /* (37) sort_list ::= sort_item */
    71,  /* (38) sort_list ::= sort_list COMMA sort_item */
    72,  /* (39) sort_item ::= expression */
    72,  /* (40) sort_item ::= expression ASC */
    72,  /* (41) sort_item ::= expression DESC */
    58,  /* (42) limit_clause ::= LIMIT INTEGER */
    59,  /* (43) skip_clause ::= SKIP INTEGER */
    68,  /* (44) expression ::= or_expression */
    73,  /* (45) or_expression ::= and_expression */
    73,  /* (46) or_expression ::= or_expression OR and_expression */
    74,  /* (47) and_expression ::= equality_expression */
    74,  /* (48) and_expression ::= and_expression AND equality_expression */
    75,  /* (49) equality_expression ::= relational_expression */
    75,  /* (50) equality_expression ::= equality_expression EQ relational_expression */
    75,  /* (51) equality_expression ::= equality_expression NE relational_expression */
    76,  /* (52) relational_expression ::= additive_expression */
    76,  /* (53) relational_expression ::= relational_expression LT additive_expression */
    76,  /* (54) relational_expression ::= relational_expression LE additive_expression */
    76,  /* (55) relational_expression ::= relational_expression GT additive_expression */
    76,  /* (56) relational_expression ::= relational_expression GE additive_expression */
    77,  /* (57) additive_expression ::= multiplicative_expression */
    77,  /* (58) additive_expression ::= additive_expression PLUS multiplicative_expression */
    77,  /* (59) additive_expression ::= additive_expression MINUS multiplicative_expression */
    78,  /* (60) multiplicative_expression ::= unary_expression */
    78,  /* (61) multiplicative_expression ::= multiplicative_expression MULT unary_expression */
    78,  /* (62) multiplicative_expression ::= multiplicative_expression DIV unary_expression */
    79,  /* (63) unary_expression ::= primary_expression */
    79,  /* (64) unary_expression ::= NOT primary_expression */
    79,  /* (65) unary_expression ::= MINUS primary_expression */
    80,  /* (66) primary_expression ::= literal */
    80,  /* (67) primary_expression ::= IDENTIFIER */
    80,  /* (68) primary_expression ::= property_expression */
    80,  /* (69) primary_expression ::= LPAREN expression RPAREN */
    82,  /* (70) property_expression ::= IDENTIFIER DOT IDENTIFIER */
    81,  /* (71) literal ::= INTEGER */
    81,  /* (72) literal ::= FLOAT */
    81,  /* (73) literal ::= STRING */
    81,  /* (74) literal ::= BOOLEAN */
    81,  /* (75) literal ::= NULL */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) cypher_query ::= query */
   -1,  /* (1) query ::= single_query */
   -1,  /* (2) query ::= union_query */
   -3,  /* (3) union_query ::= single_query UNION single_query */
   -3,  /* (4) union_query ::= union_query UNION single_query */
   -2,  /* (5) single_query ::= reading_clause_list return_clause */
   -3,  /* (6) single_query ::= reading_clause_list return_clause order_by_clause */
   -3,  /* (7) single_query ::= reading_clause_list return_clause limit_clause */
   -3,  /* (8) single_query ::= reading_clause_list return_clause skip_clause */
   -1,  /* (9) reading_clause_list ::= reading_clause */
   -2,  /* (10) reading_clause_list ::= reading_clause_list reading_clause */
   -1,  /* (11) reading_clause ::= match_clause */
   -1,  /* (12) reading_clause ::= where_clause */
   -2,  /* (13) match_clause ::= MATCH pattern_list */
   -3,  /* (14) match_clause ::= OPTIONAL MATCH pattern_list */
   -1,  /* (15) pattern_list ::= pattern */
   -3,  /* (16) pattern_list ::= pattern_list COMMA pattern */
   -1,  /* (17) pattern ::= node_pattern */
   -3,  /* (18) pattern ::= node_pattern relationship_pattern node_pattern */
   -2,  /* (19) node_pattern ::= LPAREN RPAREN */
   -3,  /* (20) node_pattern ::= LPAREN IDENTIFIER RPAREN */
   -4,  /* (21) node_pattern ::= LPAREN IDENTIFIER node_labels RPAREN */
   -2,  /* (22) node_labels ::= COLON IDENTIFIER */
   -3,  /* (23) node_labels ::= node_labels COLON IDENTIFIER */
   -4,  /* (24) relationship_pattern ::= DASH LBRACKET RBRACKET DASH */
   -5,  /* (25) relationship_pattern ::= DASH LBRACKET IDENTIFIER RBRACKET DASH */
   -7,  /* (26) relationship_pattern ::= DASH LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET DASH */
   -7,  /* (27) relationship_pattern ::= DASH LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET ARROW_RIGHT */
   -7,  /* (28) relationship_pattern ::= ARROW_LEFT LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET DASH */
   -2,  /* (29) where_clause ::= WHERE expression */
   -2,  /* (30) return_clause ::= RETURN projection_list */
   -3,  /* (31) return_clause ::= RETURN DISTINCT projection_list */
   -1,  /* (32) projection_list ::= projection_item */
   -3,  /* (33) projection_list ::= projection_list COMMA projection_item */
   -1,  /* (34) projection_item ::= expression */
   -3,  /* (35) projection_item ::= expression AS IDENTIFIER */
   -3,  /* (36) order_by_clause ::= ORDER BY sort_list */
   -1,  /* (37) sort_list ::= sort_item */
   -3,  /* (38) sort_list ::= sort_list COMMA sort_item */
   -1,  /* (39) sort_item ::= expression */
   -2,  /* (40) sort_item ::= expression ASC */
   -2,  /* (41) sort_item ::= expression DESC */
   -2,  /* (42) limit_clause ::= LIMIT INTEGER */
   -2,  /* (43) skip_clause ::= SKIP INTEGER */
   -1,  /* (44) expression ::= or_expression */
   -1,  /* (45) or_expression ::= and_expression */
   -3,  /* (46) or_expression ::= or_expression OR and_expression */
   -1,  /* (47) and_expression ::= equality_expression */
   -3,  /* (48) and_expression ::= and_expression AND equality_expression */
   -1,  /* (49) equality_expression ::= relational_expression */
   -3,  /* (50) equality_expression ::= equality_expression EQ relational_expression */
   -3,  /* (51) equality_expression ::= equality_expression NE relational_expression */
   -1,  /* (52) relational_expression ::= additive_expression */
   -3,  /* (53) relational_expression ::= relational_expression LT additive_expression */
   -3,  /* (54) relational_expression ::= relational_expression LE additive_expression */
   -3,  /* (55) relational_expression ::= relational_expression GT additive_expression */
   -3,  /* (56) relational_expression ::= relational_expression GE additive_expression */
   -1,  /* (57) additive_expression ::= multiplicative_expression */
   -3,  /* (58) additive_expression ::= additive_expression PLUS multiplicative_expression */
   -3,  /* (59) additive_expression ::= additive_expression MINUS multiplicative_expression */
   -1,  /* (60) multiplicative_expression ::= unary_expression */
   -3,  /* (61) multiplicative_expression ::= multiplicative_expression MULT unary_expression */
   -3,  /* (62) multiplicative_expression ::= multiplicative_expression DIV unary_expression */
   -1,  /* (63) unary_expression ::= primary_expression */
   -2,  /* (64) unary_expression ::= NOT primary_expression */
   -2,  /* (65) unary_expression ::= MINUS primary_expression */
   -1,  /* (66) primary_expression ::= literal */
   -1,  /* (67) primary_expression ::= IDENTIFIER */
   -1,  /* (68) primary_expression ::= property_expression */
   -3,  /* (69) primary_expression ::= LPAREN expression RPAREN */
   -3,  /* (70) property_expression ::= IDENTIFIER DOT IDENTIFIER */
   -1,  /* (71) literal ::= INTEGER */
   -1,  /* (72) literal ::= FLOAT */
   -1,  /* (73) literal ::= STRING */
   -1,  /* (74) literal ::= BOOLEAN */
   -1,  /* (75) literal ::= NULL */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* cypher_query ::= query */
#line 52 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = yymsp[0].minor.yy8;
  pState->pResult = yylhsminor.yy8;
}
#line 1251 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 1: /* query ::= single_query */
#line 57 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_QUERY, 0, 0);
  if( yylhsminor.yy8 ) cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
}
#line 1260 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 2: /* query ::= union_query */
      case 9: /* reading_clause_list ::= reading_clause */ yytestcase(yyruleno==9);
#line 62 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = yymsp[0].minor.yy8;
}
#line 1269 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 3: /* union_query ::= single_query UNION single_query */
#line 66 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_UNION, 0, 0);
  if( yylhsminor.yy8 ) {
    cypherAstAddChild(yylhsminor.yy8, yymsp[-2].minor.yy8);
    cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
  }
}
#line 1281 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 4: /* union_query ::= union_query UNION single_query */
      case 33: /* projection_list ::= projection_list COMMA projection_item */ yytestcase(yyruleno==33);
      case 38: /* sort_list ::= sort_list COMMA sort_item */ yytestcase(yyruleno==38);
#line 74 "grammar/cypher.lemon"
{
  if( yymsp[-2].minor.yy8 ) {
    cypherAstAddChild(yymsp[-2].minor.yy8, yymsp[0].minor.yy8);
    yylhsminor.yy8 = yymsp[-2].minor.yy8;
  }
}
#line 1294 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 5: /* single_query ::= reading_clause_list return_clause */
#line 84 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_SINGLE_QUERY, 0, 0);
  if( yylhsminor.yy8 ) {
    cypherAstAddChild(yylhsminor.yy8, yymsp[-1].minor.yy8);
    cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
  }
}
#line 1306 "grammar/cypher.c"
  yymsp[-1].minor.yy8 = yylhsminor.yy8;
        break;
      case 6: /* single_query ::= reading_clause_list return_clause order_by_clause */
      case 7: /* single_query ::= reading_clause_list return_clause limit_clause */ yytestcase(yyruleno==7);
      case 8: /* single_query ::= reading_clause_list return_clause skip_clause */ yytestcase(yyruleno==8);
#line 92 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_SINGLE_QUERY, 0, 0);
  if( yylhsminor.yy8 ) {
    cypherAstAddChild(yylhsminor.yy8, yymsp[-2].minor.yy8);
    cypherAstAddChild(yylhsminor.yy8, yymsp[-1].minor.yy8);
    cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
  }
}
#line 1321 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 10: /* reading_clause_list ::= reading_clause_list reading_clause */
#line 126 "grammar/cypher.lemon"
{
  /* Create a list node if needed */
  if( yymsp[-1].minor.yy8 ) {
    cypherAstAddChild(yymsp[-1].minor.yy8, yymsp[0].minor.yy8);
    yylhsminor.yy8 = yymsp[-1].minor.yy8;
  } else {
    yylhsminor.yy8 = yymsp[0].minor.yy8;
  }
}
#line 1335 "grammar/cypher.c"
  yymsp[-1].minor.yy8 = yylhsminor.yy8;
        break;
      case 11: /* reading_clause ::= match_clause */
      case 12: /* reading_clause ::= where_clause */ yytestcase(yyruleno==12);
      case 15: /* pattern_list ::= pattern */ yytestcase(yyruleno==15);
      case 17: /* pattern ::= node_pattern */ yytestcase(yyruleno==17);
      case 44: /* expression ::= or_expression */ yytestcase(yyruleno==44);
      case 45: /* or_expression ::= and_expression */ yytestcase(yyruleno==45);
      case 47: /* and_expression ::= equality_expression */ yytestcase(yyruleno==47);
      case 49: /* equality_expression ::= relational_expression */ yytestcase(yyruleno==49);
      case 52: /* relational_expression ::= additive_expression */ yytestcase(yyruleno==52);
      case 57: /* additive_expression ::= multiplicative_expression */ yytestcase(yyruleno==57);
      case 60: /* multiplicative_expression ::= unary_expression */ yytestcase(yyruleno==60);
      case 63: /* unary_expression ::= primary_expression */ yytestcase(yyruleno==63);
      case 66: /* primary_expression ::= literal */ yytestcase(yyruleno==66);
      case 68: /* primary_expression ::= property_expression */ yytestcase(yyruleno==68);
#line 136 "grammar/cypher.lemon"
{ yylhsminor.yy8 = yymsp[0].minor.yy8; }
#line 1354 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 13: /* match_clause ::= MATCH pattern_list */
#line 142 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_MATCH, yymsp[-1].minor.yy0->iLine, yymsp[-1].minor.yy0->iColumn);
  if( yylhsminor.yy8 ) cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
}
#line 1363 "grammar/cypher.c"
  yymsp[-1].minor.yy8 = yylhsminor.yy8;
        break;
      case 14: /* match_clause ::= OPTIONAL MATCH pattern_list */
#line 147 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_OPTIONAL_MATCH, yymsp[-2].minor.yy0->iLine, yymsp[-2].minor.yy0->iColumn);
  if( yylhsminor.yy8 ) cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
}
#line 1372 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 16: /* pattern_list ::= pattern_list COMMA pattern */
#line 156 "grammar/cypher.lemon"
{
  if( yymsp[-2].minor.yy8 ) {
    cypherAstAddChild(yymsp[-2].minor.yy8, yymsp[0].minor.yy8);
    yylhsminor.yy8 = yymsp[-2].minor.yy8;
  } else {
    yylhsminor.yy8 = yymsp[0].minor.yy8;
  }
}
#line 1385 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 18: /* pattern ::= node_pattern relationship_pattern node_pattern */
#line 169 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_PATH, 0, 0);
  if( yylhsminor.yy8 ) {
    cypherAstAddChild(yylhsminor.yy8, yymsp[-2].minor.yy8);
    cypherAstAddChild(yylhsminor.yy8, yymsp[-1].minor.yy8);
    cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
  }
}
#line 1398 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 19: /* node_pattern ::= LPAREN RPAREN */
#line 181 "grammar/cypher.lemon"
{
  yymsp[-1].minor.yy8 = cypherAstCreate(CYPHER_AST_NODE_PATTERN, 0, 0);
}
#line 1406 "grammar/cypher.c"
        break;
      case 20: /* node_pattern ::= LPAREN IDENTIFIER RPAREN */
#line 185 "grammar/cypher.lemon"
{
  yymsp[-2].minor.yy8 = cypherAstCreate(CYPHER_AST_NODE_PATTERN, 0, 0);
  if( yymsp[-2].minor.yy8 ) {
    CypherAst *pId = cypherAstCreateIdentifier(yymsp[-1].minor.yy0->zValue, yymsp[-1].minor.yy0->iLine, yymsp[-1].minor.yy0->iColumn);
    if( pId ) cypherAstAddChild(yymsp[-2].minor.yy8, pId);
  }
}
#line 1417 "grammar/cypher.c"
        break;
      case 21: /* node_pattern ::= LPAREN IDENTIFIER node_labels RPAREN */
#line 193 "grammar/cypher.lemon"
{
  yymsp[-3].minor.yy8 = cypherAstCreate(CYPHER_AST_NODE_PATTERN, 0, 0);
  if( yymsp[-3].minor.yy8 ) {
    CypherAst *pId = cypherAstCreateIdentifier(yymsp[-2].minor.yy0->zValue, yymsp[-2].minor.yy0->iLine, yymsp[-2].minor.yy0->iColumn);
    if( pId ) cypherAstAddChild(yymsp[-3].minor.yy8, pId);
    cypherAstAddChild(yymsp[-3].minor.yy8, yymsp[-1].minor.yy8);
  }
}
#line 1429 "grammar/cypher.c"
        break;
      case 22: /* node_labels ::= COLON IDENTIFIER */
#line 205 "grammar/cypher.lemon"
{
  yymsp[-1].minor.yy8 = cypherAstCreate(CYPHER_AST_LABELS, 0, 0);
  if( yymsp[-1].minor.yy8 ) {
    CypherAst *pLabel = cypherAstCreateIdentifier(yymsp[0].minor.yy0->zValue, yymsp[0].minor.yy0->iLine, yymsp[0].minor.yy0->iColumn);
    if( pLabel ) cypherAstAddChild(yymsp[-1].minor.yy8, pLabel);
  }
}
#line 1440 "grammar/cypher.c"
        break;
      case 23: /* node_labels ::= node_labels COLON IDENTIFIER */
#line 213 "grammar/cypher.lemon"
{
  if( yymsp[-2].minor.yy8 ) {
    CypherAst *pLabel = cypherAstCreateIdentifier(yymsp[0].minor.yy0->zValue, yymsp[0].minor.yy0->iLine, yymsp[0].minor.yy0->iColumn);
    if( pLabel ) cypherAstAddChild(yymsp[-2].minor.yy8, pLabel);
    yylhsminor.yy8 = yymsp[-2].minor.yy8;
  }
}
#line 1451 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 24: /* relationship_pattern ::= DASH LBRACKET RBRACKET DASH */
#line 224 "grammar/cypher.lemon"
{
  yymsp[-3].minor.yy8 = cypherAstCreate(CYPHER_AST_REL_PATTERN, 0, 0);
}
#line 1459 "grammar/cypher.c"
        break;
      case 25: /* relationship_pattern ::= DASH LBRACKET IDENTIFIER RBRACKET DASH */
#line 228 "grammar/cypher.lemon"
{
  yymsp[-4].minor.yy8 = cypherAstCreate(CYPHER_AST_REL_PATTERN, 0, 0);
  if( yymsp[-4].minor.yy8 ) {
    CypherAst *pId = cypherAstCreateIdentifier(yymsp[-2].minor.yy0->zValue, yymsp[-2].minor.yy0->iLine, yymsp[-2].minor.yy0->iColumn);
    if( pId ) cypherAstAddChild(yymsp[-4].minor.yy8, pId);
  }
}
#line 1470 "grammar/cypher.c"
        break;
      case 26: /* relationship_pattern ::= DASH LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET DASH */
#line 236 "grammar/cypher.lemon"
{
  yymsp[-6].minor.yy8 = cypherAstCreate(CYPHER_AST_REL_PATTERN, 0, 0);
  if( yymsp[-6].minor.yy8 ) {
    CypherAst *pId = cypherAstCreateIdentifier(yymsp[-4].minor.yy0->zValue, yymsp[-4].minor.yy0->iLine, yymsp[-4].minor.yy0->iColumn);
    CypherAst *pType = cypherAstCreateIdentifier(yymsp[-2].minor.yy0->zValue, yymsp[-2].minor.yy0->iLine, yymsp[-2].minor.yy0->iColumn);
    if( pId && pType ) {
      cypherAstAddChild(yymsp[-6].minor.yy8, pId);
      cypherAstAddChild(yymsp[-6].minor.yy8, pType);
    }
  }
}
#line 1485 "grammar/cypher.c"
        break;
      case 27: /* relationship_pattern ::= DASH LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET ARROW_RIGHT */
#line 248 "grammar/cypher.lemon"
{
  yymsp[-6].minor.yy8 = cypherAstCreate(CYPHER_AST_REL_PATTERN, 0, 0);
  if( yymsp[-6].minor.yy8 ) {
    CypherAst *pId = cypherAstCreateIdentifier(yymsp[-4].minor.yy0->zValue, yymsp[-4].minor.yy0->iLine, yymsp[-4].minor.yy0->iColumn);
    CypherAst *pType = cypherAstCreateIdentifier(yymsp[-2].minor.yy0->zValue, yymsp[-2].minor.yy0->iLine, yymsp[-2].minor.yy0->iColumn);
    if( pId && pType ) {
      cypherAstAddChild(yymsp[-6].minor.yy8, pId);
      cypherAstAddChild(yymsp[-6].minor.yy8, pType);
    }
    cypherAstSetValue(yymsp[-6].minor.yy8, "->");
  }
}
#line 1501 "grammar/cypher.c"
        break;
      case 28: /* relationship_pattern ::= ARROW_LEFT LBRACKET IDENTIFIER COLON IDENTIFIER RBRACKET DASH */
#line 261 "grammar/cypher.lemon"
{
  yymsp[-6].minor.yy8 = cypherAstCreate(CYPHER_AST_REL_PATTERN, 0, 0);
  if( yymsp[-6].minor.yy8 ) {
    CypherAst *pId = cypherAstCreateIdentifier(yymsp[-4].minor.yy0->zValue, yymsp[-4].minor.yy0->iLine, yymsp[-4].minor.yy0->iColumn);
    CypherAst *pType = cypherAstCreateIdentifier(yymsp[-2].minor.yy0->zValue, yymsp[-2].minor.yy0->iLine, yymsp[-2].minor.yy0->iColumn);
    if( pId && pType ) {
      cypherAstAddChild(yymsp[-6].minor.yy8, pId);
      cypherAstAddChild(yymsp[-6].minor.yy8, pType);
    }
    cypherAstSetValue(yymsp[-6].minor.yy8, "<-");
  }
}
#line 1517 "grammar/cypher.c"
        break;
      case 29: /* where_clause ::= WHERE expression */
#line 277 "grammar/cypher.lemon"
{
  yymsp[-1].minor.yy8 = cypherAstCreate(CYPHER_AST_WHERE, 0, 0);
  if( yymsp[-1].minor.yy8 ) cypherAstAddChild(yymsp[-1].minor.yy8, yymsp[0].minor.yy8);
}
#line 1525 "grammar/cypher.c"
        break;
      case 30: /* return_clause ::= RETURN projection_list */
#line 285 "grammar/cypher.lemon"
{
  yymsp[-1].minor.yy8 = cypherAstCreate(CYPHER_AST_RETURN, 0, 0);
  if( yymsp[-1].minor.yy8 ) cypherAstAddChild(yymsp[-1].minor.yy8, yymsp[0].minor.yy8);
}
#line 1533 "grammar/cypher.c"
        break;
      case 31: /* return_clause ::= RETURN DISTINCT projection_list */
#line 290 "grammar/cypher.lemon"
{
  yymsp[-2].minor.yy8 = cypherAstCreate(CYPHER_AST_RETURN, 0, 0);
  if( yymsp[-2].minor.yy8 ) {
    cypherAstAddChild(yymsp[-2].minor.yy8, yymsp[0].minor.yy8);
    /* Set DISTINCT flag */
    yymsp[-2].minor.yy8->iFlags |= 1;
  }
}
#line 1545 "grammar/cypher.c"
        break;
      case 32: /* projection_list ::= projection_item */
#line 302 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_PROJECTION_LIST, 0, 0);
  if( yylhsminor.yy8 ) cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
}
#line 1553 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 34: /* projection_item ::= expression */
#line 314 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_PROJECTION_ITEM, 0, 0);
  if( yylhsminor.yy8 ) cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
}
#line 1562 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 35: /* projection_item ::= expression AS IDENTIFIER */
#line 319 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_PROJECTION_ITEM, 0, 0);
  if( yylhsminor.yy8 ) {
    cypherAstAddChild(yylhsminor.yy8, yymsp[-2].minor.yy8);
    CypherAst *pAlias = cypherAstCreateIdentifier(yymsp[0].minor.yy0->zValue, yymsp[0].minor.yy0->iLine, yymsp[0].minor.yy0->iColumn);
    if( pAlias ) cypherAstAddChild(yylhsminor.yy8, pAlias);
  }
}
#line 1575 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 36: /* order_by_clause ::= ORDER BY sort_list */
#line 331 "grammar/cypher.lemon"
{
  yymsp[-2].minor.yy8 = cypherAstCreate(CYPHER_AST_ORDER_BY, 0, 0);
  if( yymsp[-2].minor.yy8 ) cypherAstAddChild(yymsp[-2].minor.yy8, yymsp[0].minor.yy8);
}
#line 1584 "grammar/cypher.c"
        break;
      case 37: /* sort_list ::= sort_item */
#line 336 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_SORT_LIST, 0, 0);
  if( yylhsminor.yy8 ) cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
}
#line 1592 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 39: /* sort_item ::= expression */
#line 348 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_SORT_ITEM, 0, 0);
  if( yylhsminor.yy8 ) cypherAstAddChild(yylhsminor.yy8, yymsp[0].minor.yy8);
}
#line 1601 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 40: /* sort_item ::= expression ASC */
#line 353 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_SORT_ITEM, 0, 0);
  if( yylhsminor.yy8 ) {
    cypherAstAddChild(yylhsminor.yy8, yymsp[-1].minor.yy8);
    cypherAstSetValue(yylhsminor.yy8, "ASC");
  }
}
#line 1613 "grammar/cypher.c"
  yymsp[-1].minor.yy8 = yylhsminor.yy8;
        break;
      case 41: /* sort_item ::= expression DESC */
#line 361 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreate(CYPHER_AST_SORT_ITEM, 0, 0);
  if( yylhsminor.yy8 ) {
    cypherAstAddChild(yylhsminor.yy8, yymsp[-1].minor.yy8);
    cypherAstSetValue(yylhsminor.yy8, "DESC");
  }
}
#line 1625 "grammar/cypher.c"
  yymsp[-1].minor.yy8 = yylhsminor.yy8;
        break;
      case 42: /* limit_clause ::= LIMIT INTEGER */
#line 372 "grammar/cypher.lemon"
{
  yymsp[-1].minor.yy8 = cypherAstCreate(CYPHER_AST_LIMIT, 0, 0);
  if( yymsp[-1].minor.yy8 ) {
    CypherAst *pLimit = cypherAstCreateLiteral(yymsp[0].minor.yy0->zValue, yymsp[0].minor.yy0->iLine, yymsp[0].minor.yy0->iColumn);
    if( pLimit ) cypherAstAddChild(yymsp[-1].minor.yy8, pLimit);
  }
}
#line 1637 "grammar/cypher.c"
        break;
      case 43: /* skip_clause ::= SKIP INTEGER */
#line 383 "grammar/cypher.lemon"
{
  yymsp[-1].minor.yy8 = cypherAstCreate(CYPHER_AST_SKIP, 0, 0);
  if( yymsp[-1].minor.yy8 ) {
    CypherAst *pSkip = cypherAstCreateLiteral(yymsp[0].minor.yy0->zValue, yymsp[0].minor.yy0->iLine, yymsp[0].minor.yy0->iColumn);
    if( pSkip ) cypherAstAddChild(yymsp[-1].minor.yy8, pSkip);
  }
}
#line 1648 "grammar/cypher.c"
        break;
      case 46: /* or_expression ::= or_expression OR and_expression */
#line 397 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("OR", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1655 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 48: /* and_expression ::= and_expression AND equality_expression */
#line 402 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("AND", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1663 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 50: /* equality_expression ::= equality_expression EQ relational_expression */
#line 407 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("=", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1671 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 51: /* equality_expression ::= equality_expression NE relational_expression */
#line 410 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("<>", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1679 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 53: /* relational_expression ::= relational_expression LT additive_expression */
#line 415 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("<", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1687 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 54: /* relational_expression ::= relational_expression LE additive_expression */
#line 418 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("<=", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1695 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 55: /* relational_expression ::= relational_expression GT additive_expression */
#line 421 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp(">", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1703 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 56: /* relational_expression ::= relational_expression GE additive_expression */
#line 424 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp(">=", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1711 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 58: /* additive_expression ::= additive_expression PLUS multiplicative_expression */
#line 429 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("+", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1719 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 59: /* additive_expression ::= additive_expression MINUS multiplicative_expression */
#line 432 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("-", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1727 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 61: /* multiplicative_expression ::= multiplicative_expression MULT unary_expression */
#line 437 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("*", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1735 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 62: /* multiplicative_expression ::= multiplicative_expression DIV unary_expression */
#line 440 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateBinaryOp("/", yymsp[-2].minor.yy8, yymsp[0].minor.yy8, 0, 0);
}
#line 1743 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 64: /* unary_expression ::= NOT primary_expression */
#line 445 "grammar/cypher.lemon"
{
  yymsp[-1].minor.yy8 = cypherAstCreate(CYPHER_AST_UNARY_OP, 0, 0);
  if( yymsp[-1].minor.yy8 ) {
    cypherAstSetValue(yymsp[-1].minor.yy8, "NOT");
    cypherAstAddChild(yymsp[-1].minor.yy8, yymsp[0].minor.yy8);
  }
}
#line 1755 "grammar/cypher.c"
        break;
      case 65: /* unary_expression ::= MINUS primary_expression */
#line 452 "grammar/cypher.lemon"
{
  yymsp[-1].minor.yy8 = cypherAstCreate(CYPHER_AST_UNARY_OP, 0, 0);
  if( yymsp[-1].minor.yy8 ) {
    cypherAstSetValue(yymsp[-1].minor.yy8, "-");
    cypherAstAddChild(yymsp[-1].minor.yy8, yymsp[0].minor.yy8);
  }
}
#line 1766 "grammar/cypher.c"
        break;
      case 67: /* primary_expression ::= IDENTIFIER */
#line 461 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateIdentifier(yymsp[0].minor.yy0->zValue, yymsp[0].minor.yy0->iLine, yymsp[0].minor.yy0->iColumn);
}
#line 1773 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 69: /* primary_expression ::= LPAREN expression RPAREN */
#line 465 "grammar/cypher.lemon"
{ yymsp[-2].minor.yy8 = yymsp[-1].minor.yy8; }
#line 1779 "grammar/cypher.c"
        break;
      case 70: /* property_expression ::= IDENTIFIER DOT IDENTIFIER */
#line 467 "grammar/cypher.lemon"
{
  CypherAst *pObj = cypherAstCreateIdentifier(yymsp[-2].minor.yy0->zValue, yymsp[-2].minor.yy0->iLine, yymsp[-2].minor.yy0->iColumn);
  yylhsminor.yy8 = cypherAstCreateProperty(pObj, yymsp[0].minor.yy0->zValue, yymsp[0].minor.yy0->iLine, yymsp[0].minor.yy0->iColumn);
}
#line 1787 "grammar/cypher.c"
  yymsp[-2].minor.yy8 = yylhsminor.yy8;
        break;
      case 71: /* literal ::= INTEGER */
      case 72: /* literal ::= FLOAT */ yytestcase(yyruleno==72);
      case 73: /* literal ::= STRING */ yytestcase(yyruleno==73);
      case 74: /* literal ::= BOOLEAN */ yytestcase(yyruleno==74);
#line 475 "grammar/cypher.lemon"
{
  yylhsminor.yy8 = cypherAstCreateLiteral(yymsp[0].minor.yy0->zValue, yymsp[0].minor.yy0->iLine, yymsp[0].minor.yy0->iColumn);
}
#line 1798 "grammar/cypher.c"
  yymsp[0].minor.yy8 = yylhsminor.yy8;
        break;
      case 75: /* literal ::= NULL */
#line 487 "grammar/cypher.lemon"
{
  yymsp[0].minor.yy8 = cypherAstCreateLiteral("null", 0, 0);
}
#line 1806 "grammar/cypher.c"
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 45 "grammar/cypher.lemon"

  pState->zError = (char*)"Parser failed due to stack overflow";
#line 1853 "grammar/cypher.c"
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 41 "grammar/cypher.lemon"

  pState->zError = (char*)"Syntax error in Cypher query";
#line 1875 "grammar/cypher.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
